-- Schema for the control-plane database — single source of truth.
--
-- Mounted into the postgres image at /docker-entrypoint-initdb.d and run once,
-- on first initialisation of an empty data volume. To re-apply after editing,
-- recreate the volume (docker compose down -v): initdb scripts run only on a
-- fresh data directory. This is fine pre-deployment; a real migration tool
-- (Alembic) takes over once there is data worth keeping.
--
-- Foreign keys and checks are named explicitly so a future Alembic setup can
-- reference them for ALTER/DROP instead of guessing autogenerated names. When
-- Alembic is wired, set a matching SQLAlchemy naming_convention (or rename here
-- on a fresh volume) so autogenerate doesn't churn on name mismatches.
--
-- Tables are ordered so referenced tables (users) precede their referrers.

-- ============================= core: auth & registry =============================

-- Users: login by name, soft-deleted via deleted_at, role drives gating.
-- id is integer (security.create_token(user_id: int)); IDENTITY auto-fills it
-- so seed_admin can INSERT (name, role, password_hash) without an id.
CREATE TABLE users (
    id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name          TEXT        NOT NULL,
    password_hash TEXT        NOT NULL,
    role          TEXT        NOT NULL DEFAULT 'user'
                  CONSTRAINT users_role_check CHECK (role IN ('admin', 'user')),
    deleted_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- One active account per name; a soft-deleted name can be reused.
CREATE UNIQUE INDEX users_name_active_idx ON users (name) WHERE deleted_at IS NULL;

-- Robots: registry rows. upsert never sets `enabled`, so new rows default
-- enabled and a re-save preserves the existing value. key_name is a *soft*
-- reference to secrets.name — deliberately NOT a foreign key, so a robot may
-- point at a key that is absent (the dashboard renders that as "missing")
-- without the row being illegal.
CREATE TABLE robots (
    robot_id   TEXT        PRIMARY KEY,
    host       TEXT        NOT NULL,
    ssh_user   TEXT        NOT NULL DEFAULT 'root',
    agent_port INTEGER     NOT NULL DEFAULT 9000,
    key_name   TEXT,
    enabled    BOOLEAN     NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Secrets: Fernet ciphertext, decrypted only in memory by the vault.
-- ciphertext is BYTEA: put_secret binds fernet.encrypt(...) (bytes) and
-- get_secret does bytes(row["ciphertext"]) — both require binary storage.
CREATE TABLE secrets (
    name       TEXT        PRIMARY KEY,
    ciphertext BYTEA       NOT NULL,
    kind       TEXT        NOT NULL DEFAULT 'other',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================== protocol authoring ==============================

-- Labware library: opentrons labware-definition JSON, referenced by filename
-- from a config's PlateInfo.type. Uploads may replace an existing definition;
-- created_by/created_at hold the original author, updated_by/updated_at the
-- last writer, so a replace of a shared definition stays traceable.
--
-- The provenance FKs are RESTRICT-on-delete by default, which is intended:
-- users are soft-deleted (never hard-deleted), and blocking a hard delete of a
-- user who authored labware is the correct audit behaviour.
CREATE TABLE labware (
    name        TEXT        PRIMARY KEY,
    definition  JSONB       NOT NULL,
    created_by  BIGINT      CONSTRAINT labware_created_by_fkey REFERENCES users (id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by  BIGINT      CONSTRAINT labware_updated_by_fkey REFERENCES users (id),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Deck configs: a saved BaseConfig (pipettes, core_plates, stock_plates),
-- authored in the UI. The one object used for both agent launch and the
-- simulation check; stored whole so there is no second structure to drift.
-- Deck configs are versioned and owned. Each save writes a NEW row (immutable
-- history), version increments within an (owner, name) family. Heritage of a
-- fork is stored as a SNAPSHOT (origin_owner_name / origin_name / origin_version),
-- not a foreign key, so it stays true even after the source is edited or deleted.
-- Versions are semver (major.minor.patch), auto-classified on save from a diff
-- against the family head: major = labware/pipette set, minor = positions/offsets,
-- patch = well contents. The highest changed axis bumps, lower axes reset. Editing
-- a non-head version does not branch in-family, it forks into a new family (heritage
-- snapshot), so a family stays a single line ordered by (major, minor, patch).
CREATE TABLE deck_configs (
    id                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    owner              BIGINT      NOT NULL
                       CONSTRAINT deck_configs_owner_fkey REFERENCES users (id),
    name               TEXT        NOT NULL,
    major              INTEGER     NOT NULL,
    minor              INTEGER     NOT NULL,
    patch              INTEGER     NOT NULL,
    config             JSONB       NOT NULL,
    origin_owner_name  TEXT,
    origin_name        TEXT,
    origin_major       INTEGER,
    origin_minor       INTEGER,
    origin_patch       INTEGER,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT deck_configs_family_version_key UNIQUE (owner, name, major, minor, patch)
);

-- ============================== user onboarding ==============================

-- Invite codes: an admin issues a single-use code carrying the role the new
-- account will receive; a user redeems it at /register. The CHECK permits
-- 'admin' for future use, but the issue endpoint only mints 'user' — an admin
-- code is a bearer credential and is reached instead by promoting an existing
-- user. used_by/used_at are set atomically on redemption (consume guard).
CREATE TABLE user_invites (
    code        TEXT        PRIMARY KEY,
    target_role TEXT        NOT NULL DEFAULT 'user'
                CONSTRAINT user_invites_role_check CHECK (target_role IN ('admin', 'user')),
    created_by  BIGINT      CONSTRAINT user_invites_created_by_fkey REFERENCES users (id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    used_by     BIGINT      CONSTRAINT user_invites_used_by_fkey REFERENCES users (id),
    used_at     TIMESTAMPTZ,
    expires_at  TIMESTAMPTZ
);

-- ============================== standard units ==============================

-- Standard units: opentrons load-name strings the user picks from when building
-- a deck (modules like tipracks and reservoirs, and pipette models). These are
-- plain strings, unlike custom labware which is a JSONB definition, so they live
-- in their own table rather than as null-definition rows in labware. Shared and
-- user-writable (with the add_labware permission), so created_by is kept to
-- trace who added a bad string to everyone's dropdown.
CREATE TABLE standard_units (
    name        TEXT        PRIMARY KEY,
    category    TEXT        NOT NULL
                CONSTRAINT standard_units_category_check CHECK (category IN ('module', 'pipette')),
    created_by  BIGINT      CONSTRAINT standard_units_created_by_fkey REFERENCES users (id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================== permissions ==============================

-- Per-user capability flags. Capabilities are data (strings), not columns, so a
-- new one (add_action later) is a new row, never a migration. No CHECK on
-- permission for the same reason. Admins bypass this table entirely (the check
-- is role == 'admin' OR a matching row), so admins are never granted rows.
CREATE TABLE user_permissions (
    user_id     BIGINT      NOT NULL
                CONSTRAINT user_permissions_user_fkey REFERENCES users (id),
    permission  TEXT        NOT NULL,
    granted_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT user_permissions_pkey PRIMARY KEY (user_id, permission)
);

-- ============================== methods ==============================

-- Liquid-handling methods a manual user may select per step. These map to
-- driver functions in the drivers repo (LIQUID_METHODS), so exposing one is an
-- admin decision after reviewing the code, not an auto-discovered list. params
-- is the hyperparameter spec the admin publishes: a list of
-- {name, units?, min?, max?} the frontend renders as fillable fields.
-- basic_liquid_transfer has no hyperparameters and is the universal default,
-- seeded here so it is always available regardless of admin action.
CREATE TABLE methods (
    name        TEXT        PRIMARY KEY,
    params      JSONB       NOT NULL DEFAULT '[]'::jsonb,
    created_by  BIGINT      CONSTRAINT methods_created_by_fkey REFERENCES users (id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO methods (name, params) VALUES ('basic_liquid_transfer', '[]'::jsonb);


-- ============================== action_plans ==============================

-- A protocol plan: an ordered list of steps pinned to one deck config version.
-- Same versioned/owned/heritage shape as deck_configs. steps is the plan wire
-- format (the same shape the actions editor serializes as a draft): a list of
-- add_stock / move_core step envelopes. Versions are semver, auto-classified on
-- save: major = the step set and what each step does, minor = order and methods,
-- patch = volumes. Pinned config_id is a specific deck_configs row, so the plan
-- borrows that version's plates and substances.
CREATE TABLE action_plans (
    id                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    owner              BIGINT      NOT NULL
                       CONSTRAINT action_plans_owner_fkey REFERENCES users (id),
    name               TEXT        NOT NULL,
    major              INTEGER     NOT NULL,
    minor              INTEGER     NOT NULL,
    patch              INTEGER     NOT NULL,
    config_id          BIGINT      NOT NULL
                       CONSTRAINT action_plans_config_fkey REFERENCES deck_configs (id),
    steps              JSONB       NOT NULL,
    origin_owner_name  TEXT,
    origin_name        TEXT,
    origin_major       INTEGER,
    origin_minor       INTEGER,
    origin_patch       INTEGER,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT action_plans_family_version_key UNIQUE (owner, name, major, minor, patch)
);


-- ============================== drafts ==============================

-- Unsaved editor state. Deliberately dumb: a JSONB blob with NO validation, NO
-- versioning, NO heritage, and no FK into the versioned tables. A draft is
-- allowed to be broken (half-filled, no pipette, dangling refs) precisely
-- because it is not a version. One draft per user per kind (config or plan).
-- A successful save into the versioned entity deletes it; the user can also
-- discard it explicitly. Saving is explicit (a button), never autosaved.
CREATE TABLE drafts (
    user_id     BIGINT      NOT NULL
                CONSTRAINT drafts_user_fkey REFERENCES users (id),
    kind        TEXT        NOT NULL
                CONSTRAINT drafts_kind_check CHECK (kind IN ('config', 'plan')),
    content     JSONB       NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT drafts_pkey PRIMARY KEY (user_id, kind)
);